name: Deployment Pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  build_test_deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          ENV_TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          ENV_SECRET: ${{ secrets.SECRET }}
          ENV_PORT: ${{ secrets.PORT }}
      - name: move .env into backend
        run: mv .env './backend/'
      - name: npm install backend
        run: cd './backend/' && npm install
      - name: npm install frontend
        run: cd './frontend/' && npm install
      - name: lint backend
        run: cd './backend/' && npm run lint
      - name: lint frontend
        run: cd './frontend/' && npm run lint
      - name: build ui
        run: cd './backend/' && npm run build:ui
      - name: test backend
        run: cd './backend/' && npm run test
      - name: test frontend
        run: cd './frontend/' && npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start:backend, npm run start
          working-directory: frontend
          wait-on: http://localhost:3003,http://localhost:3000
      - name: deploy to heroku
        if: ${{ (github.event_name == 'push') && (!contains(join(github.event.commits.*.message, ','), '#skip')) }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "full-stack-bloglist"
          heroku_email: "thushan.perera95@gmail.com"
          healthcheck: "https://full-stack-bloglist.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          appdir: "backend"

  tag_release:
    needs: [build_test_deploy]
    runs-on: ubuntu-20.04
    if: ${{ (github.event_name == 'push') && (!contains(join(github.event.commits.*.message, ','), '#skip')) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
